theme: jekyll-theme-minimal

title: [Fusion Ecology]
description: [Ecology; evolution; mathematics; statistics; systematics; geochemistry; computer vision]

minimal:
  social_links:
    twitter: tomezard
